name: Create Test File

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create file
        run: echo "Automation is working" > automation-test.txt

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add automation-test.txt
          git commit -m "Add test file" || exit 0
          git push
